version: '3.8'

services:
  app:
    container_name: my_project_app
    build: .
    ports:
      - 8083:8083
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/toiletdb1
      DATABASE_USERNAME: toilet1
      DATABASE_PASSWORD: toiletpassword
    depends_on:
      - db
    restart: always

  db:
    container_name: my_project_postgres
    image: postgres
    environment:
      - POSTGRES_DB=toiletdb1
      - POSTGRES_USER=toilet1
      - POSTGRES_PASSWORD=toiletpassword
    ports:
      - 5432:5432
    volumes:
      - C:\postgres_con:/var/lib/postgres/data
    restart: always

