spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/toiletdb1}
    username: ${DATABASE_USERNAME:toilet1}
    password: ${DATABASE_PASSWORD:toiletpassword}
    driver-class-name: org.postgresql.Driver
server:
  port: 8083
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 1440m
